from sigma.pipelines.common import (
    logsource_linux_file_create,
    logsource_linux_network_connection,
    logsource_linux_process_creation,
    logsource_macos_file_create,
    logsource_macos_process_creation,
    logsource_windows_file_event,
    logsource_windows_image_load,
    logsource_windows_network_connection,
    logsource_windows_process_creation,
    logsource_windows_registry_event,
    logsource_windows_registry_set,
)

# Future logsource helpers we may enable later:
# from sigma.pipelines.common import (
#     logsource_windows_file_access,
#     logsource_windows_file_change,
#     logsource_windows_file_delete,
#     logsource_windows_file_rename,
#     logsource_windows_registry_add,
#     logsource_windows_registry_delete,
# )

# Rule categories -> rule conditions
CATEGORY_TO_CONDITIONS_MAPPINGS = {
    "windows_process_creation": logsource_windows_process_creation(),
    "windows_image_load": logsource_windows_image_load(),
    "windows_file_event": logsource_windows_file_event(),
    "windows_network_connection": logsource_windows_network_connection(),
    "windows_registry_event": logsource_windows_registry_event(),
    "windows_registry_set": logsource_windows_registry_set(),
    "linux_process_creation": logsource_linux_process_creation(),
    "linux_network_connection": logsource_linux_network_connection(),
    "linux_file_create": logsource_linux_file_create(),
    "macos_process_creation": logsource_macos_process_creation(),
    "macos_file_create": logsource_macos_file_create(),
}

# Generic mappings that apply to all rule categories.
GENERIC_FIELD_MAPPINGS = {
    "User": "user.name",
    "UserName": "user.name",
    "LogonId": "user.logon_id",
}

# Rule category -> field mappings
CATEGORY_FIELD_MAPPINGS = {
    "windows_process_creation": {
        "Image": "process.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "ParentImage": "process.parent_path",
        "ParentProcessName": "process.parent_name",
        "ParentCommandLine": "process.parent_command_line",
        "CurrentDirectory": "process.working_directory",
        "IntegrityLevel": "process.integrity_level",
        "sha256": "process.hash_sha256",
        "sha1": "process.hash_sha1",
        "md5": "process.hash_md5",
    },
    "windows_image_load": {
        "Image": "process.path",
        "ImageLoaded": "module.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "sha256": "module.hash_sha256",
        "sha1": "module.hash_sha1",
        "md5": "module.hash_md5",
    },
    "windows_file_event": {
        "Image": "process.path",
        "TargetFilename": "file.path",
        "FileName": "file.name",
        "sha256": "file.hash_sha256",
        "sha1": "file.hash_sha1",
        "md5": "file.hash_md5",
    },
    "windows_network_connection": {
        "Image": "process.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "Protocol": "network.protocol",
        "SourceIp": "network.source_ip",
        "SourcePort": "network.source_port",
        "DestinationIp": "network.destination_ip",
        "DestinationPort": "network.destination_port",
        "DestinationHostname": "network.destination_domain",
    },
    "windows_registry_event": {
        "Image": "process.path",
        "TargetObject": "registry.key_path",
        "RegistryKey": "registry.key_path",
        "RegistryValueName": "registry.value_name",
        "RegistryValueData": "registry.value_data",
        "Details": "registry.value_data",
    },
    "windows_registry_set": {
        "Image": "process.path",
        "TargetObject": "registry.key_path",
        "RegistryKey": "registry.key_path",
        "RegistryValueName": "registry.value_name",
        "RegistryValueData": "registry.value_data",
        "Details": "registry.value_data",
    },
    "linux_process_creation": {
        "Image": "process.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "ParentImage": "process.parent_path",
        "ParentProcessName": "process.parent_name",
        "ParentCommandLine": "process.parent_command_line",
        "CurrentDirectory": "process.working_directory",
        "sha256": "process.hash_sha256",
        "sha1": "process.hash_sha1",
        "md5": "process.hash_md5",
    },
    "linux_network_connection": {
        "Image": "process.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "Protocol": "network.protocol",
        "SourceIp": "network.source_ip",
        "SourcePort": "network.source_port",
        "DestinationIp": "network.destination_ip",
        "DestinationPort": "network.destination_port",
        "DestinationHostname": "network.destination_domain",
    },
    "linux_file_create": {
        "Image": "process.path",
        "TargetFilename": "file.path",
        "FileName": "file.name",
        "sha256": "file.hash_sha256",
        "sha1": "file.hash_sha1",
        "md5": "file.hash_md5",
    },
    "macos_process_creation": {
        "Image": "process.path",
        "ProcessName": "process.name",
        "CommandLine": "process.command_line",
        "ParentImage": "process.parent_path",
        "ParentProcessName": "process.parent_name",
        "ParentCommandLine": "process.parent_command_line",
        "CurrentDirectory": "process.working_directory",
        "sha256": "process.hash_sha256",
        "sha1": "process.hash_sha1",
        "md5": "process.hash_md5",
    },
    "macos_file_create": {
        "Image": "process.path",
        "TargetFilename": "file.path",
        "FileName": "file.name",
        "sha256": "file.hash_sha256",
        "sha1": "file.hash_sha1",
        "md5": "file.hash_md5",
    },
}
